"""Static configuration for the sync script.

Tweak the constants here when the layout, integration name, or strip
rules change — the rest of the script stays the same.
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]

DOMAIN = "neopool"

# Snapshot of the ruff config from home-assistant/core@dev/pyproject.toml
# — used to lint the generated dist/ tree exactly the way core's CI would.
# Keeps the custom repo's lighter ruff config (in the root pyproject.toml)
# untouched.
RUFF_DIST_CONFIG = Path(__file__).resolve().parent / "ruff_dist.toml"

SOURCE_INTEGRATION = REPO_ROOT / "custom_components" / DOMAIN
SOURCE_TESTS = REPO_ROOT / "tests"

# Mirrors the Home Assistant core repo layout so a `diff -r dist/neopool
# <core>/homeassistant/components/neopool` works directly.
#
# `DIST_PARENT` (`dist/`) holds lint helpers (ruff.toml, .ruff_cache)
# that the sync script needs but that don't belong inside the
# core-shaped output tree — only `DIST_ROOT` (`dist/neopool/`) is meant
# to be copy-pasted into a core checkout.
DIST_PARENT = REPO_ROOT / "dist"
DIST_ROOT = DIST_PARENT / DOMAIN
DEST_INTEGRATION = DIST_ROOT / "homeassistant" / "components" / DOMAIN
DEST_TESTS = DIST_ROOT / "tests" / "components" / DOMAIN
DEST_SNAPSHOTS = DEST_TESTS / "snapshots"

# ---------------------------------------------------------------------------
# Files & directories that stay HACS-only
# ---------------------------------------------------------------------------

# Integration files NOT to copy into core.
EXCLUDE_INTEGRATION_FILES: frozenset[str] = frozenset(
    {
        "migration.py",  # cross-domain (vistapool→neopool) + v1→v4 history
    }
)

EXCLUDE_INTEGRATION_DIRS: frozenset[str] = frozenset(
    {
        "brand",  # HACS UI logos; core uses the central brands repo
        "__pycache__",
    }
)

# Translation files to copy into core. Core integrations ship only
# `translations/en.json` (the English build artefact); all other locales
# are generated by Lokalise and committed via the translation bot, never
# by the integration author. This is an allow-list — adding new locales
# to `custom_components/neopool/translations/` won't accidentally leak
# them into the core sync output.
INCLUDE_TRANSLATION_FILES: frozenset[str] = frozenset({"en.json"})

# Test files NOT to copy into core.
EXCLUDE_TEST_FILES: frozenset[str] = frozenset(
    {
        "test_migration.py",  # custom-only; matches the stripped migration.py
        "test_init_custom.py",  # vistapool/v1/legacy migration scenarios
        "test_config_flow_custom.py",  # vistapool import + v1 duplicate abort
    }
)

EXCLUDE_TEST_DIRS: frozenset[str] = frozenset({"__pycache__"})

# ---------------------------------------------------------------------------
# Path & import rewrites
# ---------------------------------------------------------------------------

# Plain string replacements applied to every Python file copied to dist.
# Order matters — longer matches first, so the more specific replacement
# does not get partially eaten by a later one.
PYTHON_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    # patch("custom_components.neopool…")  →  patch("homeassistant.components.neopool…")
    ('"custom_components.neopool', '"homeassistant.components.neopool'),
    ("'custom_components.neopool", "'homeassistant.components.neopool"),
    # `from custom_components.neopool…`  /  `import custom_components.neopool…`
    ("from custom_components.neopool", "from homeassistant.components.neopool"),
    ("import custom_components.neopool", "import homeassistant.components.neopool"),
    # phacc → core test helpers. The order matters: the explicit `.common`
    # alias would match the generic rule too, but listing it first is just
    # belt-and-braces — both forms produce the same final string.
    #
    #   phacc.common      → tests.common
    #   phacc.components  → tests.components
    #   phacc.typing      → tests.typing
    #   phacc.syrupy      → tests.syrupy
    ("pytest_homeassistant_custom_component", "tests"),
)

# ---------------------------------------------------------------------------
# Manifest transform
# ---------------------------------------------------------------------------

# HACS-only top-level keys to drop from manifest.json.
MANIFEST_DROP_KEYS: frozenset[str] = frozenset({"version", "issue_tracker"})

# Whether to rewrite `>=X.Y.Z` requirement specifiers to the equivalent
# exact pin `==X.Y.Z` when emitting the core-shaped manifest. The custom
# HACS package keeps `>=` so HACS users pip-install any compatible
# upstream release; core integrations pin the requirement exactly so
# every Home Assistant release ships against a known, audited library
# version. Verified against platinum/gold integrations (peblar,
# airgradient, elgato, wled, aiohue, aioshelly, zha) — all use `==`.
MANIFEST_PIN_REQUIREMENTS: bool = True

# Manifest fields where the custom value differs from what core expects.
# Applied verbatim to the parsed manifest.json before re-emitting, so the
# custom repo can keep its HACS-shaped value (e.g. the GitHub repo URL
# under `documentation`) while the core mirror gets the canonical form.
MANIFEST_OVERRIDES: dict[str, object] = {
    "documentation": f"https://www.home-assistant.io/integrations/{DOMAIN}",
    # Drop the "Modbus" suffix from the user-facing integration name. The
    # custom HACS package keeps "NeoPool Modbus" so HACS users can tell it
    # apart from any future core package; the core entry just reads
    # "NeoPool" so the protocol detail does not clutter the integration
    # picker for end users.
    "name": "NeoPool",
    # Quality scale tier the integration targets in core. The custom
    # manifest omits this key (HACS doesn't surface it), but core
    # integrations declare it explicitly so hassfest can validate the
    # corresponding `quality_scale.yaml` rules.
    "quality_scale": "platinum",
}

# JSON key paths to delete from `strings.json` and `translations/en.json`.
# Each entry is a dot-separated path through the nested JSON object —
# `config.step.import_from_vistapool` removes that whole subtree.
# Used to strip vistapool/migration UI strings that have no counterpart
# in the core integration.
JSON_DROP_KEYS: tuple[str, ...] = (
    "config.step.import_from_vistapool",
    "config.abort.migration_complete",
    "config.abort.migration_failed",
    "issues.domain_renamed",
    "issues.domain_rename_partial_failure",
)

# ---------------------------------------------------------------------------
# Optional strippers (toggled via CLI flags)
# ---------------------------------------------------------------------------

# Default behaviour: strip license headers (core does not use them) and
# keep `# pragma: no cover` markers (some core integrations do use them).
DEFAULT_STRIP_LICENSE = True
DEFAULT_STRIP_PRAGMA = False

# Default: emit raw UTF-8 in `translations/en.json` — readable in
# editors and grep. Opt in to `\uXXXX` escapes via `--escape-translations`
# when matching upstream's Lokalise serialisation byte-for-byte matters
# (e.g. for a clean diff against an existing en.json that was written
# by the translation pipeline).
DEFAULT_ESCAPE_TRANSLATIONS = False

# License header detection: the first non-empty line starts with this
# prefix, and the contiguous comment block that follows is the header.
LICENSE_HEADER_PREFIX = "# Copyright"
