name: Hassfest

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - "custom_components/neopool/**"
  pull_request:
    paths:
      - "custom_components/neopool/**"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
